DROP TABLE IF EXISTS "role_menus";
DROP TABLE IF EXISTS "menu_apis";
DROP TABLE IF EXISTS "apis";
DROP TABLE IF EXISTS "api_groups";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "menus";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "users";