app:
  csrf: false
  debug: true
  mode: dev
  name: adminx
  ssl: false
  version: v0.0.1
  welcome: 欢迎使用 adminx
db:
  driver: postgres
  source: postgresql://root:secret@localhost:5432/adminx?sslmode=disable
redis:
  addr: 127.0.0.1:6379
  pass:
  db: 0
  maxretries: 2
  poolsize: 2
  minidleconns: 2
server:
  addr: :8080
  readtimeout: 1s
  wirtetimeout: 1s
token:
  accesstokenduration: 15m
  refreshtokenduration: 24h
mail:
  host: 
  port: 465
  user: 
  pass: 
  to:
verifycode:
  keyprefix: adminx
  expiretime: 15
