// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountMenusByParent(ctx context.Context, dollar_1 []int64) (int64, error)
	// CreateApiGroup 创建 api组
	CreateApiGroup(ctx context.Context, arg CreateApiGroupParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) (*Menu, error)
	CreateMenuApi(ctx context.Context, arg []CreateMenuApiParams) *CreateMenuApiBatchResults
	CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteMenu(ctx context.Context, dollar_1 []int64) error
	DeleteMenuApiByMenuAndApi(ctx context.Context, arg DeleteMenuApiByMenuAndApiParams) error
	GetSession(ctx context.Context, id uuid.UUID) (*Session, error)
	GetUser(ctx context.Context, username string) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByPhone(ctx context.Context, phone string) (*User, error)
	ListApiByIDs(ctx context.Context, dollar_1 []int64) ([]*Api, error)
	ListApiGroup(ctx context.Context, key string) ([]*ApiGroup, error)
	ListMenuApiForApiByMenu(ctx context.Context, menu int64) ([]int64, error)
	ListMenuByParent(ctx context.Context, parent int64) ([]*Menu, error)
	ListMenusByType(ctx context.Context, dollar_1 []int32) ([]*Menu, error)
}

var _ Querier = (*Queries)(nil)
