// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountMenusByParent(ctx context.Context, dollar_1 []int64) (int64, error)
	CreateApi(ctx context.Context, arg CreateApiParams) error
	// CreateApiGroup 创建 api 组
	CreateApiGroup(ctx context.Context, arg CreateApiGroupParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) (*Menu, error)
	CreateMenuApi(ctx context.Context, arg []CreateMenuApiParams) *CreateMenuApiBatchResults
	CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteApi(ctx context.Context, id []int64) error
	// DeleteApiGroup 删除 Api 组
	DeleteApiGroup(ctx context.Context, dollar_1 []int64) error
	DeleteMenu(ctx context.Context, dollar_1 []int64) error
	DeleteMenuApiByMenuAndApi(ctx context.Context, arg DeleteMenuApiByMenuAndApiParams) error
	GetSession(ctx context.Context, id uuid.UUID) (*Session, error)
	GetUser(ctx context.Context, username string) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByPhone(ctx context.Context, phone string) (*User, error)
	ListApi(ctx context.Context, arg ListApiParams) ([]*Api, error)
	ListApiByGroup(ctx context.Context, dollar_1 []int64) ([]*Api, error)
	ListApiByIDs(ctx context.Context, dollar_1 []int64) ([]*Api, error)
	ListApiGroup(ctx context.Context, arg ListApiGroupParams) ([]*ApiGroup, error)
	ListMenuApiByApi(ctx context.Context, api []int64) ([]*MenuApi, error)
	ListMenuApiForApiByMenu(ctx context.Context, menu int64) ([]int64, error)
	ListMenuByParent(ctx context.Context, parent int64) ([]*Menu, error)
	ListMenusByType(ctx context.Context, dollar_1 []int32) ([]*Menu, error)
	UpdateApi(ctx context.Context, arg UpdateApiParams) error
	// UpdateApiGroup 修改 api 组
	UpdateApiGroup(ctx context.Context, arg UpdateApiGroupParams) error
}

var _ Querier = (*Queries)(nil)
