// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: version.sql

package db

import (
	"context"
)

const selectVersion = `-- name: SelectVersion :one
SELECT version() as ver
`

func (q *Queries) SelectVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, selectVersion)
	var ver string
	err := row.Scan(&ver)
	return ver, err
}
