name: Golang lint

on:
  push:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.15
      
      -
        run: go env -w GOPRIVATE=github.com/gostack-labs

      - 
        uses: actions/checkout@v2
        
      - 
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2