name: Golang lint

on:
  push:

permissions:
  contents: read

env:
  GOPRIVATE: "github.com/gostack-labs"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: ^1.15
      
      - name: Set up GOPRIVATE
        env:
          TOKEN: ${{ secrets.GOPRIVATE_TOKEN}}
        run: git config --global url."https://bytegolang:${TOKEN}@github.com".insteadOf "https://github.com"

      - 
        uses: actions/checkout@v2

      - 
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2